### ISSUE TITLE
Task 1: Create a baseline logo for the hive

### ISSUE THREAD

**Issue by ruphy** [WikiToLearn/Hives-Network#1]
Create a basic logo which can be used as template from the different hives

**Comment by learneradarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/18267421/26734036/56ebf044-47da-11e7-9978-8f44463bab68.png)

**Comment by learneradarsh** [comment]
I think it'll complete your logo need.

**Comment by learneradarsh** [comment]
I've pulled a request with a random file name containing a logo, see it and let me know.

**Comment by kowalski7cc** [comment]
![hives-01](https://cloud.githubusercontent.com/assets/5065094/26753650/2c418bc4-486b-11e7-81a4-897f0f4ece12.png)
I designed something more oriented to the original wikitolearn logo, using same color accents.
Font: Open Sans Bold

**Comment by kowalski7cc** [comment]
![hives-01](https://cloud.githubusercontent.com/assets/5065094/26753659/7245fe0c-486b-11e7-8946-d1e6490c66a7.png)
I designed something more oriented to the original wikitolearn logo, using same color accents.
Font: Open Sans Bold

**Comment by kowalski7cc** [comment]
![hives city mono-01](https://cloud.githubusercontent.com/assets/5065094/26754365/e59815bc-4879-11e7-8eff-f8e9e53ce88e.png)
Updated with city/hive name

**Comment by ruphy** [comment]
it rocks, thanks!!
